name: Haskell Release Nightly
on:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: write

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            echoCalName: echoCal-latest-linux-x86_64
            writeCalName: writeCal-latest-linux-x86_64
          - os: macOS-latest
            echoCalName: echoCal-latest-darwin-aarch64
            writeCalName: writeCal-latest-darwin-aarch64
          - os: windows-latest
            echoCalName: echoCal-latest-windows-x86_64.exe
            writeCalName: writeCal-latest-windows-x86_64.exe
        
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.12.2'
        cabal-version: '3.14.2.0'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal new-build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
    - name: Get executable path of echoCal
      id: get-path-echoCal
      run: echo "path=$(cabal list-bin echoCal)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Upload echoCal binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.get-path-echoCal.outputs.path }}
        asset_name: ${{ matrix.echoCalName }}
        tag: latest
        overwrite: true
        prerelease: true
    - name: Get executable path of writeCal
      id: get-path-writeCal
      run: echo "path=$(cabal list-bin writeCal)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Upload writeCal binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.get-path-writeCal.outputs.path }}
        asset_name: ${{ matrix.writeCalName }}
        tag: latest
        overwrite: true
        prerelease: true